server:
  port: 50000

spring:
  banner:
    image:
      location: "classpath:banner.txt"

management:
  endpoint:
    health:
      group:
        readiness:
          include: "*"
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: ${ENV_MONITORING_PATH:/}

app:
  game_version_name: "${GAME_VERSION:red}"
  max_cache_expiry_in_minutes: 12
  pokemon_io_host_url: "https://pokeapi.co"
  shakespeare_translator_host_url: "https://api.funtranslations.com"