---
apiVersion: v1
kind: Namespace
metadata:
  name: information-ns
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: pokemon-information-service-config-map
  namespace: information-ns
data:
  database: mongodb
  database_uri: mongodb://localhost:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-information-service
  namespace: information-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: pokemon-information-service
  template:
    metadata:
      labels:
        app: pokemon-information-service
    spec:
      containers:
        - name: pokemon-information-service
          image: ojoadeolagabriel/pokemon-information-service:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 50000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 50000
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 50000
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: pokemon-information-service-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-information-service-service
  namespace: information-ns
spec:
  selector:
    app: pokemon-information-service
  ports:
    - port: 50002
      targetPort: 50000
  type: LoadBalancer